// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $(".popSelector").on("click", function() {
      return $(this).toggleClass("on");
    }).on("mouseleave", function() {
      return $(this).removeClass("on");
    });
    if ($.browser.msie && $.browser.version === "6.0") {
      return $(".dropNav,.dropNav li").on("hover", function(e) {
        return $(this).toggleClass("hover", e.type === "mouseenter");
      });
    }
  });

}).call(this);
